name = "stock-tracker"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "STOCK_DATA"
id = "f7845bb8f6c048f0b658ac01797ced0b"
preview_id = "f7845bb8f6c048f0b658ac01797ced0b"

[[d1_databases]]
binding = "DB"
database_name = "stock-tracker-db"
database_id = "8451af7d-ba5b-47b3-915f-8aee5fa82723"
migrations_dir = "migrations"

[observability]
enabled = true

[triggers]
crons = [
  "0 13 * * 1-5",       # 下午 21:00 (UTC 13) 历史同步 [一至五]
  "0 19 * * 1-6",       # 凌晨 03:00 (UTC 19) 增量归档 [一至六]
  "*/1 1-7 * * 1-5"     # 盘中实时行情 (09:00-15:00 UTC 1-7)
]
